theme: jekyll-theme-dinky
show_downloads: False
baseurl: /cl
title: ML
email: kermorvant@teklia.com
description: >- # this means to ignore newlines until "baseurl:"
  Authors : Christopher Kermorvant
markdown: kramdown
