theme: jekyll-theme-dinky
show_downloads: False
baseurl: /csexed-ml
title: Introduction to Machine Learning in Python
email: kermorvant@teklia.com
description: >- # this means to ignore newlines until "baseurl:"
  Authors : Christopher Kermorvant
